//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Data2CodeWPF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L2Data2CodeWPF.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate code while {0} is open by an IDE, close IDE to activate Generate button.
        /// </summary>
        public static string CannotGenerateCode {
            get {
                return ResourceManager.GetString("CannotGenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful code generation.
        /// </summary>
        public static string CodeGeneratedOK {
            get {
                return ResourceManager.GetString("CodeGeneratedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful, the settings have changed! The application will restart ... Do you want to continue?.
        /// </summary>
        public static string ConfigChanged {
            get {
                return ResourceManager.GetString("ConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source.
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the contents of folder {0}?.
        /// </summary>
        public static string DeleteContents {
            get {
                return ResourceManager.GetString("DeleteContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit templates.
        /// </summary>
        public static string EditTemplates {
            get {
                return ResourceManager.GetString("EditTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty folders before generating code.
        /// </summary>
        public static string EmptyFolders {
            get {
                return ResourceManager.GetString("EmptyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access local database.
        /// </summary>
        public static string ErrorDb {
            get {
                return ResourceManager.GetString("ErrorDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description server (DbSchema) not available, ask to one of these people:.
        /// </summary>
        public static string ErrorDBSchema {
            get {
                return ResourceManager.GetString("ErrorDBSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description server (DbSchema) not available, but local copy of descriptions is available.
        /// </summary>
        public static string ErrorDbSchemaButFile {
            get {
                return ResourceManager.GetString("ErrorDbSchemaButFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution is open and cannot be modified.
        /// </summary>
        public static string ErrorSlnOpened {
            get {
                return ResourceManager.GetString("ErrorSlnOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only genereate JSON file.
        /// </summary>
        public static string GenerateOnlyJson {
            get {
                return ResourceManager.GetString("GenerateOnlyJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message board.
        /// </summary>
        public static string MessageBoard {
            get {
                return ResourceManager.GetString("MessageBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tables selected. Do you want to continue?.
        /// </summary>
        public static string NoTablesSelected {
            get {
                return ResourceManager.GetString("NoTablesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only elements will be added, nothing will be deleted.
        /// </summary>
        public static string NothingToDelete {
            get {
                return ResourceManager.GetString("NothingToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open generated folder.
        /// </summary>
        public static string OpenGeneratedFolder {
            get {
                return ResourceManager.GetString("OpenGeneratedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PowerShell at output directory.
        /// </summary>
        public static string OpenPSCommand {
            get {
                return ResourceManager.GetString("OpenPSCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app settings.
        /// </summary>
        public static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open vars window.
        /// </summary>
        public static string OpenVarsWindow {
            get {
                return ResourceManager.GetString("OpenVarsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open output with Visual Studio Code.
        /// </summary>
        public static string OpenVSC {
            get {
                return ResourceManager.GetString("OpenVSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open solution file with Visual Studio.
        /// </summary>
        public static string OpenVSSolution {
            get {
                return ResourceManager.GetString("OpenVSSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder not created.
        /// </summary>
        public static string OutputFolderNotCreated {
            get {
                return ResourceManager.GetString("OutputFolderNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Tables.
        /// </summary>
        public static string RelatedTables {
            get {
                return ResourceManager.GetString("RelatedTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save at....
        /// </summary>
        public static string SaveAt {
            get {
                return ResourceManager.GetString("SaveAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically select related tables.
        /// </summary>
        public static string SelectRelatedTables {
            get {
                return ResourceManager.GetString("SelectRelatedTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables &amp; Views.
        /// </summary>
        public static string TablesViews {
            get {
                return ResourceManager.GetString("TablesViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2 Data2Code.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Configuration.
        /// </summary>
        public static string Vars {
            get {
                return ResourceManager.GetString("Vars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string VarsTitle {
            get {
                return ResourceManager.GetString("VarsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
