//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Data2CodeUI.Shared.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L2Data2CodeUI.Shared.Localize.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added code to git.
        /// </summary>
        public static string AddedCodeToGit {
            get {
                return ResourceManager.GetString("AddedCodeToGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful code generation.
        /// </summary>
        public static string CodeGeneratedOK {
            get {
                return ResourceManager.GetString("CodeGeneratedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful, the settings have changed! The application will restart ... Do you want to continue?.
        /// </summary>
        public static string ConfigChanged {
            get {
                return ResourceManager.GetString("ConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove folders because of template configuration.
        /// </summary>
        public static string ErrorCannotRemoveFolders {
            get {
                return ResourceManager.GetString("ErrorCannotRemoveFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to database.
        /// </summary>
        public static string ErrorConnectToDb {
            get {
                return ResourceManager.GetString("ErrorConnectToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        public static string ErrorDb {
            get {
                return ResourceManager.GetString("ErrorDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description server (DbSchema) not available.
        /// </summary>
        public static string ErrorDBSchema {
            get {
                return ResourceManager.GetString("ErrorDBSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description server (DbSchema) not available, but local copy of descriptions is available.
        /// </summary>
        public static string ErrorDbSchemaButFile {
            get {
                return ResourceManager.GetString("ErrorDbSchemaButFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path &apos;{0}&apos;.
        /// </summary>
        public static string ErrorFindPath {
            get {
                return ResourceManager.GetString("ErrorFindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating code.
        /// </summary>
        public static string ErrorGeneratingCode {
            get {
                return ResourceManager.GetString("ErrorGeneratingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to get template path.
        /// </summary>
        public static string ErrorGettingTemplatePath {
            get {
                return ResourceManager.GetString("ErrorGettingTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load template, perhaps variables are malformed or templates names are not consistent. Open templates to find the problem.
        /// </summary>
        public static string ErrorLoadingTemplate {
            get {
                return ResourceManager.GetString("ErrorLoadingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read word list.
        /// </summary>
        public static string ErrorLoadingWordList {
            get {
                return ResourceManager.GetString("ErrorLoadingWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading schema.
        /// </summary>
        public static string ErrorReadingSchema {
            get {
                return ResourceManager.GetString("ErrorReadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing folders.
        /// </summary>
        public static string ErrorRemovingFolders {
            get {
                return ResourceManager.GetString("ErrorRemovingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resource {0} not found at path {1}.
        /// </summary>
        public static string ErrorResourceNotFound {
            get {
                return ResourceManager.GetString("ErrorResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when serializing options.
        /// </summary>
        public static string ErrorSerializingOptions {
            get {
                return ResourceManager.GetString("ErrorSerializingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution is open and cannot be modified.
        /// </summary>
        public static string ErrorSlnOpened {
            get {
                return ResourceManager.GetString("ErrorSlnOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git is not in this system or it has problems.
        /// </summary>
        public static string ErrorWithGit {
            get {
                return ResourceManager.GetString("ErrorWithGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git repo not found.
        /// </summary>
        public static string NoGitRepo {
            get {
                return ResourceManager.GetString("NoGitRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tables selected. Do you want to continue?.
        /// </summary>
        public static string NoTablesSelected {
            get {
                return ResourceManager.GetString("NoTablesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only elements will be added, nothing will be deleted.
        /// </summary>
        public static string NothingToDelete {
            get {
                return ResourceManager.GetString("NothingToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be running in background.
        /// </summary>
        public static string ParametrizedContinueMessage {
            get {
                return ResourceManager.GetString("ParametrizedContinueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not in this system or it has problems.
        /// </summary>
        public static string ParametrizedErrorMessage {
            get {
                return ResourceManager.GetString("ParametrizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing {0} process.
        /// </summary>
        public static string ParametrizedKillingMessage {
            get {
                return ResourceManager.GetString("ParametrizedKillingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is working hard... waiting another 10 seconds....
        /// </summary>
        public static string ParametrizedSlowMessage {
            get {
                return ResourceManager.GetString("ParametrizedSlowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is starting.
        /// </summary>
        public static string ParametrizedStartingProcess {
            get {
                return ResourceManager.GetString("ParametrizedStartingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} finish execution.
        /// </summary>
        public static string ParametrizedStoppingProcess {
            get {
                return ResourceManager.GetString("ParametrizedStoppingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} has been precessed.
        /// </summary>
        public static string TableProcessed {
            get {
                return ResourceManager.GetString("TableProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resource template not founded at template library.
        /// </summary>
        public static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git process is working hard... waiting another 10 seconds....
        /// </summary>
        public static string WarnGitSlow {
            get {
                return ResourceManager.GetString("WarnGitSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing Git process.
        /// </summary>
        public static string WarnKillingGit {
            get {
                return ResourceManager.GetString("WarnKillingGit", resourceCulture);
            }
        }
    }
}
